version: "3.9"
services:
  scilab:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - "./storage/app/experiment_files:/var/www/scilabApp/storage/app/experiment_files"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    restart: always
    ports:
      - 8000:8000
      - 3000:3000
    depends_on:
      - database

  database:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
