version: "3.9"
services:
    scilab:
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - "./storage/app/experiment_files:/var/lib/scilab-app/storage/app/experiment_files"
        ports:
            - 8000:8000
        depends_on:
            - database

    database:
        image: mysql:8.0
        ports:
            - 3306:3306
        restart: always
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        volumes:
            - db-data:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    db-data: ~
