<template>
  <v-list
    density="compact"
    nav
    variant="tonal"
  >
    <v-list-item
      href="/#/experiments/add"
      prepend-icon="mdi-plus-circle"
      :title="$t('CreateExperiment')"
      value="addExperiment"
    />
    <v-list-item
      href="/#/experiments"
      prepend-icon="mdi-list-box"
      :title="$t('ExperimentList')"
      value="experiments"
    />
  </v-list>
</template>
